### ISSUE TITLE
generate proper neutral colors

### ISSUE THREAD

**Issue by varemenos** [ant-design/ant-design-palettes#3]
It seems like the generate function doesn't work properly for neutral colors.

My assumption based on your color guidelines was that the generate function would also work for neutral colors but unfortunately it adds a red hue messing with the greyscale shades.

If it's too hard to refactor now, could we at least add a second parameter to the function that would try not to add any color but a palette grey shades?

<img width="1004" alt="screen shot 2018-07-30 at 11 26 53" src="https://user-images.githubusercontent.com/626343/43389243-813bb42a-93eb-11e8-8e39-436cd798b869.png">

**Comment by varemenos** [comment]
Sorry to bother you again @afc163 but now that the grey color is part of the generated palette too, could we also include in here?

https://github.com/ant-design/ant-design/blob/master/components/style/color/colors.less

**Comment by afc163** [comment]
@varemenos It may have compatibility issue but you can try it and send us PR~

**Comment by audacioustux** [comment]
no idea why this issue is closed. 'presetPalettes' returns '#000000' twice.  and not identical with https://ant.design/docs/spec/colors#Neutral-Color-Palette
```javascript
grey: ['#a6a6a6',
    '#999999',
    '#8c8c8c',
    '#808080',
    '#737373',
    '#666666',
    '#404040',
    '#1a1a1a',
    '#000000',
    '#000000',
  ],
```

**Comment by afc163** [comment]
Actually, neutral colors in https://ant.design/docs/spec/colors#Neutral-Color-Palette is hand-picked by our designers...
